title: Diabetes Pharmacology Ontology
description: DPO is used to represent diabetes patients to perform clinical reasoning tasks including diagnosis, therapy planning, and plan critiquing
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
gem "github-pages", group: :jekyll_plugins

github:
  zip_url: http://example.com/download.zip
  another_url: another value