title: Diabetes Pharmacology Ontology
description: DPO is used to represent diabetes patients to perform clinical reasoning tasks including diagnosis, therapy planning, and plan critiquing
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0